name: starflame
description: A space strategy game.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  flame: ^1.19.0
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  intl: ^0.19.0
  logger: ^1.3.0
  material_symbols_icons: ^4.2805.1
  path: ^1.9.0
  test: ^1.25.0
  vector_math: ^2.1.4
  watch_it: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/ships/
  shaders:
    - shaders/backdrop.frag
  fonts:
    - family: Chakra
      fonts:
        - asset: fonts/ChakraPetch-Light.ttf
