name: starfury
description: A space strategy game.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flame: ^1.15.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  test: ^1.24.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
