const planetNames = [
  "Castorford",
  "Polluxham",
  "Leonis Bay",
  "Arcton",
  "Zetabury",
  "Capelton",
  "Aldebar",
  "Cassiemoor",
  "Lacerta",
  "Bootis Port",
  "Centauri",
  "Fomal Bay",
  "Draconis",
  "Vegaton",
  "Hercland",
  "Indibury",
  "Reticton",
  "Persei",
  "Eridan",
  "Capriham",
  "Aquilton",
  "Monceris",
  "Dracon",
  "Serpen",
  "Cepheia",
  "Pegasford",
  "Serpfield",
  "Centbury",
  "Sagiton",
  "Scorpia",
  "Pisciham",
  "Phoenbury",
  "Canphis",
  "Antarford",
  "Ursaminor",
  "Spiceton",
  "Aurigam",
  "Carinham",
  "Crucis",
  "Velorham",
  "Audreille",
  "Epine Bat",
  "Biolanthe",
  "Cactacae",
  "Dysone",
  "Fleurvie",
  "GQuanette",
  "Vigne Encre",
  "Integral",
  "Cerf Vol",
  "Krynoide",
  "Lupinaire",
  "Mendacie",
  "Hommesvert",
  "Re'Annee",
  "Rougeherb",
  "Bois Sage",
  "Vigne Serp",
  "Serennelle",
  "Sucbine",
  "Teslain",
  "Triffide",
  "Aeglosse",
  "Athelin",
  "Feuille Roi",
  "Aranionne",
  "Elano'ee",
  "Malorne",
  "Nimelot",
  "Nifredi",
  "Herbepipe",
  "Oiolairis",
  "Symbellis",
  "Valinore",
];